server:
  enable: true
  addr: "0.0.0.0:80"
  token: "12345678901"
client:
  enable: false
  url: ""
  method: "POST"
memory:
  enable: false
  limit: 42
  frequcey: 1000
disk:
  enable: false
  frequcey: 1000
cpu:
  enable: false
  limit: 64
  frequcey: 1000
docker:
  enable: false
  frequcey: 1000 # frequcey in ms
  containers: []
health:
  enable: false
  frequcey: 1000
  urls: []
ping:
  enable: true
  frequcey: 1000
  timeout: 20
  count: 5
  ips:   [
    "10.10.0.2"
  ]
